# Per https://www.rechenschieber.org/2006/02/ultralog-0973/

brand = 'Ultra_Log'
subtitle = ''
name = '153'

[geometry]
side_wh = [9866, 1520]  # 37cm x 5.7cm
margins_xy = [0, 0]
scale_wh = [6666, 72]  # 25cm (6666.7px) x 3.5mm (93px)
tick_wh = [3, 50]
slide_h = 800  # 10 x SH
top_margin = 0

[layout]
front = 'LL/0, LL/1, LL/2, LL/3, DF [CF, CIF, SH1, SH2, CH1, TH, Ln, L, CI, C] D, LL3, LL2, LL1, LL0'
rear = 'Const, R1, R2, K, A [B, T1, T2, ST, S, P, H1, H2, CI, C] D, DI, Q1, Q2, Q3'
scale_ns = 'UltraLog'
