brand = 'Faber-Castell'
name = '2/83'
[geometry]
side_wh = [8800, 1280]  # 33cm x 4.8cm
margins_xy = [100, 100]
scale_wh = [6666, 101]  # 25cm (6666.7px) x 3.5mm (93px)
slide_h = 400  # 1.5cm
top_margin = 0
[geometry.scale_h_overrides]
front = {72 = ['K', 'T1', 'T2', 'P']}
rear = {90 = ['LL03', 'LL02', 'LL01', 'LL1', 'LL2', 'LL3']}
[layout]
front = 'K T1 T2 DF/CF CIF CI C/D S ST P'
rear = 'LL03 LL02 LL01 W2/W2Prime L C W1Prime/W1 LL1 LL2 LL3'
[layout.align_overrides]
front = { T2 = 'upper', CI = 'upper', DF = 'lower', S = 'lower' }
rear = { C = 'upper' }
[style]
font_family = 'CMUBright'
bg_colors = { C = 'FC_LIGHT_GREEN_BG', CF = 'FC_LIGHT_GREEN_BG' }
