brand = 'Aristo'
subtitle = 'Commerz II'
name = '965'
[geometry]
side_wh = [8000, 1200]  # 30cm (8000px) x 5cm (1333px)
margins_xy = [100, 100]
scale_wh = [6666, 80]  # 25cm (6666.7px) x 3.5mm (93px)
slide_h = 480  # 1.7cm (450px)
[layout]
front = 'Pct KZ [T2 P2 P1 T1] Z Libra'
scale_ns = 'Merchant'
[layout.align_overrides]
front = { P2 = 'upper' }
[style]
font_family = 'CMUBright'
decreasing_color = 'sym_green'
[style.overrides]
T1 = { color = 'red' }
T2 = { color = 'red' }
