brand = 'Aristo'
subtitle = 'Commerz II'
name = '965'
[geometry]
side_wh = [8266, 1466]  # 31cm x 5.5cm
margins_xy = [0, 0]
scale_wh = [6666, 160]  # 25cm x 3.5mm (93px)
slide_h = 480  # 1.7cm (450px)
brace_shape = false
[geometry.scale_h_overrides]
front = { 80 = ['P2', 'P1', 'T1', 'Z'] }
rear = { 80 = [ 'ZZ3', 'ZZ2', 'ZZ1', 'ZZ%', 'T1' ] }
[geometry.margin_overrides]
front = { 160 = ['£']}  # Spacer until conversion mark band is added
rear = { -5 = ['ZZ%']}
[layout]
front = 'P% KZ [T2 P2 P1 T1] Z £'
rear = ' [ ZZ3 ZZ2 ZZ1 ZZ% T1 ] '
scale_ns = 'Merchant'
[layout.align_overrides]
front = { P2 = 'upper' }
rear = { ZZ3 = 'lower' }
[style]
font_family = 'CMUBright'
decreasing_color = 'sym_green'
[style.overrides]
T1 = { color = 'red' }
T2 = { color = 'red' }
