brand = 'KWENA & TOOR CO.'
subtitle = 'LEFT HANDED LIMAÇON 2020'
name = 'BOGELEX 1000'

[geometry]
side_wh = [8000, 1600]
margins_xy = [100, 100]
scale_wh = [5600, 160]
tick_wh = [3, 70]
slide_h = 640
top_margin = 109
margin_overrides={front = {-5 = ['L', 'R2']}, rear = {80 = ['DI']}}
[layout]
front = '|  L,  DF [ CF,CIF,CI,C ] D, R1, R2 |'
rear = '|  K,  A  [ B, T, ST, S ] D,  DI    |'
[layout.align_overrides]
front = { CIF = 'upper' }
rear = { D = 'upper', DI = 'upper' }
